routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// INICIO
Route::get('/', 'web@index');

// NOSOTROS
Route::get('/nosotros', 'web@nosotros');

// JUEGOS
Route::get('/juegos', 'web@juegos');

// CONTACTO
Route::get('/contacto', 'web@contacto');

//Correo contacto
Route::post('correo-contacto', 'Correos@contacto');


// ADMINISTRADOR
Route::group(['prefix' => 'admin'], function () {
    
      Route::get('/', function () {
        return view('admin.index');
      });
    
    //########################################################
    ########//
    //################################################################//
    
    
      //Juegos
      Route::group(['prefix' => 'juegos'], function () {
        //Añadir un Juego
        Route::get('agregar', 'Juegos@create');
        //----------------------------//
      });
      //Rutas de los controladores
      Route::resource('juegos', 'Juegos');
    
    
    //################################################################//
    //################################################################//
    
    
    //Nosotros
    Route::get('nosotros', 'infos@nosotrosIndex');
    
    
    //################################################################//
    //################################################################//
    
    
    //Pagina Principal
    Route::get('pagina-principal', 'infos@principalIndex');
    
    
    //################################################################//
    //################################################################//
    

    //Contacto
    Route::get('contacto', 'infos@contactoIndex');
    
    
    //################################################################//
    //################################################################//
    //Rutas de los controladores
    Route::resource('info', 'infos');
  });
  

resources/views/admin/contacto.blade.php
<!-- extiende del layout master -->
@extends('admin.includes.admin-master')

<!-- Titulo de la pagina -->
@section('title', 'Administrador web')

<!-- Titulo de la sección -->
@section('title-page', 'Contacto')

<!-- Subtitulo de la sección -->
@section('subtitle-page', 'Editar información de contacto')

@section('navbar-somos','active')

@section('seccion-principal','Contacto')
@section('seccion-principal-url','/admin/contacto')
@section('seccion-principal-icono','fa fa-fw fa-globe')

@section('content')

<!-- contenido -->
  <div class="row">
    <div class="col-lg-12">

        <form role="form" method="POST" action={{route('info.update', $info->id)}} enctype="multipart/form-data">
          <input type="hidden" name="_method" value="PUT">
          {{ csrf_field() }}
          <div class="form-group">
              <label>Dirección de la empresa</label>
              <textarea name="direccion" class="form-control" rows="3" required="">{{$info->direccion}}</textarea>
          </div>
            <div class="clearfix"></div>
            <div class="form-group botones-admin">
              <input type="hidden" name="info" value="contacto">
              <button type="submit" class="btn btn-primary">Actualizar</button>
            </div>

        </form>

    </div>
  </div>
<!-- //contenido -->
@endsection

resources/views/admin/index.blade.php
<!-- extiende del layout master -->
@extends('admin.includes.admin-master')

<!-- Titulo de la pagina -->
@section('title', 'Administrador web')

<!-- Titulo de la sección -->
@section('title-page', 'Bienvenida')

<!-- Subtitulo de la sección -->
@section('subtitle-page', 'Pagina de Administración')

<!-- contenido -->
@section('content')
  <div class="row">

  </div>
@endsection

resources/views/admin/juegos.blade.php
<!-- extiende del layout master -->
@extends('admin.includes.admin-master')

<!-- Titulo de la pagina -->
@section('title', 'Administrador web')

<!-- Titulo de la sección -->
@section('title-page', 'Juegos')

<!-- Dropdown-menu -->
@section('navbar-juegos','active')


@section('seccion-principal','Juegos')
@section('seccion-principal-url','/admin/juegos')
@section('seccion-principal-icono','fa fa-gamepad fa-fw')

@section('content')
        @if(isset($edit))

          @include('admin.juegos.juegos-edit')

        @elseif(isset($crear))

          @include('admin.juegos.juegos-crear')

        @else

          @include('admin.juegos.juegos-lista')

        @endif
@endsection

resources/views/admin/nosotros.blade.php
<!-- extiende del layout master -->
@extends('admin.includes.admin-master')

<!-- Titulo de la pagina -->
@section('title', 'Administrador web')

<!-- Titulo de la sección -->
@section('title-page', 'Página Nosotros')

<!-- Subtitulo de la sección -->
@section('subtitle-page', 'Editar información de la página nosotros')

@section('navbar-nosotros','active')

@section('seccion-principal','Nosotros')
@section('seccion-principal-url','/admin/nosotros')
@section('seccion-principal-icono','fa fa-fw fa-users')

@section('content')

<!-- contenido -->
  <div class="row">
    <div class="col-lg-12">

        <form role="form" method="POST" action={{route('info.update', $info->id)}} enctype="multipart/form-data">
          <input type="hidden" name="_method" value="PUT">
          {{ csrf_field() }}
           <div class="form-group">
              <label>Pagina Nosotros</label>
              <textarea name="info_nosotros" id="text-editor" class="form-control" rows="3" required="">{{$info->info_nosotros}}</textarea>
          </div>
            <div class="clearfix"></div>
            <div class="form-group botones-admin">
              <input type="hidden" name="info" value="nosotros">
              <button type="submit" class="btn btn-primary">Actualizar</button>
            </div>

        </form>

    </div>
  </div>
<!-- //contenido -->
@endsection

resources/views/admin/pagina-principal.blade.php
<!-- extiende del layout master -->
@extends('admin.includes.admin-master')

<!-- Titulo de la pagina -->
@section('title', 'Administrador web')

<!-- Titulo de la sección -->
@section('title-page', 'Pagina Principal')

<!-- Subtitulo de la sección -->
@section('subtitle-page', 'Editar información de la pagina principal')

@section('navbar-somos','active')


@section('seccion-principal','Pagina Principal')
@section('seccion-principal-url','/admin/pagina-principal')
@section('seccion-principal-icono','fa fa-home')

@section('content')

<!-- contenido -->
  <div class="row">
    <div class="col-lg-12">

        <form role="form" method="POST" action={{route('info.update', $info->id)}} enctype="multipart/form-data">
          <input type="hidden" name="_method" value="PUT">
          {{ csrf_field() }}
          <div class="form-group">
              <label>Título</label>
              <input name="titulo_principal" class="form-control" maxlength="100" required="" value="{{$info->titulo_principal}}">
              <p class="help-block">(100 caracteres).</p>
              @if($errors->has('titulo'))
              <span style="color:red;">{{ $errors->first('titulo') }}</span>
              @endif
          </div>
          <div class="form-group">
              <label>Contenido</label>
              <textarea name="info_principal" id="text-editor" class="form-control" rows="3" required="">{{$info->info_principal}}</textarea>
          </div>
            <div class="clearfix"></div>
            <div class="form-group botones-admin">
              <input type="hidden" name="info" value="pagina-principal">
              <button type="submit" class="btn btn-primary">Actualizar</button>
            </div>

        </form>

    </div>
  </div>
<!-- //contenido -->
@endsection